[build]
  functions = "netlify/functions"  # Path to the functions folder
  publish = "."                # Path to your published assets (e.g., static files)

[dev]
  functions = "netlify/functions"  # Local functions directory during development
  publish = "."                # Local folder for serving static files during dev

[[redirects]]
  from = "/404.html"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/500.html"
  to = "/500.html"
  status = 500

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404